#!/usr/bin/env python3
"""Regenerate the Margin Notes review tool's manuscript content from paper/main.tex.

margin_notes.html carries, inside its main <script>, a region bounded by

    // BEGIN GENERATED by tools/margin_notes/build_doc_from_tex.py -- ...
    const CITES = {...}; function cite(...) {...}; const SECTIONS = [...]; const DOC = [...];
    // END GENERATED

This script rebuilds that region from paper/main.tex (+ main.aux for \\ref numbers,
refs.bib for CITES, numbers.json for \\val) so the DOC array never has to be
hand-mirrored again. META and all app code outside the region stay byte-identical.

Usage (Python 3.11, stdlib only):
    python tools/margin_notes/build_doc_from_tex.py            # --report (default): no writes to
                                                                # margin_notes.html; prints the id
                                                                # carry-forward report and writes
                                                                # generated_preview.html
    python tools/margin_notes/build_doc_from_tex.py --check    # exit 1 if the region is stale, the
                                                                # markers are missing, or generation
                                                                # fails (e.g. unknown \\val key)
    python tools/margin_notes/build_doc_from_tex.py --write [--allow-drop id1,id2]

Comments in the live tool are keyed by block id, so ids are carried forward:
generated blocks are aligned to the current DOC (same type, order-preserving
weighted alignment on word-level difflib similarity >= MATCH_THRESHOLD; then a
second, order-free pass for blocks that moved; footnote-style blocks are aligned
as their own sequence). Matched blocks keep their old id (figures also keep their
old `img`). An existing id that matches nothing is DROPPED (its comments would be
orphaned): --write refuses unless --allow-drop names it, and dropped ids are
recorded in a "retired ids" comment so they are never reused for a new block.
Header comment keys ("h:<id>") count as ids too.

Conventions replicated from the hand-made DOC array
---------------------------------------------------
* Blocks: paragraphs {id, tex, section, h2?, h3?, text}; tables {id, section,
  h2?, h3?, type:'table', label:'Table N', caption, headers, rows}; figures
  {id, section, ..., type:'figure', label:'Figure N', caption, img}.
* `tex` is the block's raw LaTeX (comments removed, whitespace collapsed to one
  line); `text`/`caption` are HTML template literals.  (The hand mirror had
  partially pre-rendered its tex fields; this generator keeps them raw.)
* Abstract: one block id 'abstract', section 'front', h2 'Abstract'.
* \\section -> h2, \\subsection/\\subsubsection -> h3, attached to the first
  block of that (sub)section (both keys when a section opens with a
  subsection; the app shows the h2).  Header carry-forward: if a float precedes
  the first paragraph and the old DOC put that header on a later block (e.g.
  'results-k4-1'), the header stays on that block so "h:<id>" keys survive.
  Section nav ids come from \\label{sec:<id>} (existing SECTIONS ids/labels are
  kept; new sections derive id/label).  Appendix h2 = "Appendix X: <title>".
* Paragraph = blank-line-separated chunk.  itemize and description stay inline
  in their paragraph (items joined by spaces; description items render as
  "<strong>label</strong>: body").  enumerate in the defects section is split
  one block per item, with a bold "Defect N: " lead inserted into the item's
  leading \\textbf (not literally in main.tex).  \\paragraph{X} -> bold lead.
* \\footnote{...} is removed from its block's text (no marker) and becomes a
  separate block right after it: id '<parent>-fn<k>', tex '[footnote] <raw>',
  text '<span class="footnote-block">Footnote: ...</span>'.  Appendix
  description items that reference a table (\\item[Note a (Table~\\ref{tab:x},
  ...)]) are shown the same way right after that table ('<table-id>-fn<k>',
  tex '[appendix note] ...'); the appendix keeps only its remaining prose.
* \\todo{x}/\\pending{x} -> <span class="editorial-flag">[TODO: x]</span> /
  [PENDING: x].
* Inline: \\emph/\\textit -> <em>, \\textbf -> <strong>, \\texttt -> <code>,
  -- -> &ndash;, --- -> &mdash;, ``x'' -> "x", ~ -> space, \\% \\_ \\& \\{ \\} escapes,
  {,} -> ",", < > & HTML-escaped, \\url{u} -> u.
* Math is flattened to plain text: $p=0.0015$ -> p=0.0015, $^\\dagger$ -> †,
  $\\times$ -> x, $\\sim$ -> ~, $\\ll$ -> "much less than", \\text{..} unwrapped,
  x_\\text{eff} -> x_eff, other superscripts -> <sup>..</sup>.
* \\citep/\\citet/\\cite{a,b} -> ${cite('a','b')} inside template literals (table
  cells, being plain strings, get the rendered <cite> HTML).  CITES short names
  come from refs.bib: "Last YEAR", "Last & Last YEAR", "Last et al. YEAR".
* \\ref/\\Cref resolve to main.aux numbers ('??' + warning when missing).
* \\val{key} renders numbers.json values[key].value (LaTeX, e.g. 2{,}000 ->
  2,000); a missing file/key is a hard error naming the key.  \\claim{id}{text}
  renders as text (the tex field keeps it verbatim).
* Tables: first tabular row = headers; \\multirow{n}{*}{x} -> x on its first
  row, '' below; rules/\\addlinespace dropped; an empty first cell repeats the
  row-group's label (the hand mirror's "Bibliography entry" x2 rows).
* The refs.bib table (label 'refs.bib') is generated from refs.bib at
  \\bibliography's position.
* Hand-authored blocks with no LaTeX counterpart (HAND_AUTHORED_IDS) are kept
  verbatim (raw source), placed after the block that preceded them before.
"""
from __future__ import annotations

import argparse
import difflib
import functools
import html as htmllib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
PAPER = REPO / "paper"
DEFAULT_TEX = PAPER / "main.tex"
DEFAULT_AUX = PAPER / "main.aux"
DEFAULT_BIB = PAPER / "refs.bib"
DEFAULT_NUMBERS = PAPER / "numbers.json"
DEFAULT_HTML = HERE / "margin_notes.html"
DEFAULT_PREVIEW = HERE / "generated_preview.html"

BEGIN_MARKER = ("// BEGIN GENERATED by tools/margin_notes/build_doc_from_tex.py -- "
                "edit paper/main.tex and re-run; do not hand-edit")
END_MARKER = "// END GENERATED"
RETIRED_PREFIX = "// retired ids (dropped by an earlier regeneration; never reused): "

# Old DOC blocks with no LaTeX counterpart, kept verbatim at their position.
HAND_AUTHORED_IDS = (
    "results-intro-implicit",   # synthetic lead-in carrying the Results headers
    "defects-note-numbering",   # editorial note on the ten-defects count
    "references-note",          # note above the refs.bib table
)
MATCH_THRESHOLD = 0.5    # in-order alignment
MOVED_THRESHOLD = 0.5    # order-free second pass
DIFF_REPORT_BELOW = 0.99
ABSTRACT_SECTION = ("front", "Title & abstract")
# enumerate environments split into one block per item, keyed by section id.
ENUM_SPLIT_LEADS = {"defects": "Defect {n}: "}
REFS_TABLE_ID = "references-table"
REFS_TABLE_CAPTION = "Current contents of refs.bib, read-only (edit the file directly, not here)."

CITE_FN = (
    "function cite(...keys) {\n"
    "  return ` <cite contenteditable=\"false\">(${keys.map(k => CITES[k] || k).join('; ')})</cite>`;\n"
    "}"
)
# Private-use placeholders for citation calls inside rendered text.
CITE_OPEN, CITE_CLOSE = "\ue000", "\ue001"


class GenerationError(Exception):
    """Unrecoverable input problem (unbalanced braces, missing \\val key, ...)."""


# ---------------------------------------------------------------------------
# Low-level LaTeX scanning helpers
# ---------------------------------------------------------------------------

def strip_comments(s: str) -> str:
    """Drop % comments with TeX semantics (the newline and next line's indent go too)."""
    out, i, n = [], 0, len(s)
    while i < n:
        c = s[i]
        if c == "\\" and i + 1 < n:
            out.append(s[i:i + 2])
            i += 2
            continue
        if c == "%":
            j = s.find("\n", i)
            if j == -1:
                break
            i = j + 1
            while i < n and s[i] in " \t":
                i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


def read_group(s: str, i: int) -> tuple[str, int]:
    """s[i] == '{'; return (content, index after the matching '}')."""
    if i >= len(s) or s[i] != "{":
        raise GenerationError(f"expected '{{' at offset {i}: {s[i:i + 40]!r}")
    depth, j = 0, i
    while j < len(s):
        c = s[j]
        if c == "\\":
            j += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return s[i + 1:j], j + 1
        j += 1
    raise GenerationError(f"unbalanced braces starting at: {s[i:i + 60]!r}")


def skip_ws(s: str, i: int, newlines: bool = True) -> int:
    chars = " \t\r\n" if newlines else " \t"
    while i < len(s) and s[i] in chars:
        i += 1
    return i


def read_arg(s: str, i: int) -> tuple[str, int]:
    """Read one mandatory argument: a {group} or a single token."""
    i = skip_ws(s, i)
    if i >= len(s):
        raise GenerationError("missing macro argument at end of input")
    if s[i] == "{":
        return read_group(s, i)
    if s[i] == "\\":
        m = re.match(r"\\([A-Za-z]+|.)", s[i:])
        return m.group(0), i + len(m.group(0))
    return s[i], i + 1


def read_optional(s: str, i: int) -> tuple[str | None, int]:
    """Read an optional [..] argument (braces inside are respected)."""
    j = skip_ws(s, i, newlines=False)
    if j >= len(s) or s[j] != "[":
        return None, i
    depth, k = 0, j
    while k < len(s):
        c = s[k]
        if c == "\\":
            k += 2
            continue
        if c == "{":
            _, k = read_group(s, k)
            continue
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                return s[j + 1:k], k + 1
        k += 1
    raise GenerationError(f"unterminated optional argument: {s[j:j + 60]!r}")


def find_env_end(s: str, start: int, name: str) -> tuple[int, int]:
    """Return (start, end) of the \\end{name} matching a \\begin{name} ending at `start`."""
    pat = re.compile(r"\\(begin|end)\{" + re.escape(name) + r"\}")
    depth = 1
    for m in pat.finditer(s, start):
        depth += 1 if m.group(1) == "begin" else -1
        if depth == 0:
            return m.start(), m.end()
    raise GenerationError(f"\\begin{{{name}}} without matching \\end{{{name}}}")


def split_top_level(s: str, sep: str) -> list[str]:
    """Split on `sep` ('&' or '\\\\') outside braces and nested environments."""
    parts, buf, depth, env_depth, i = [], [], 0, 0, 0
    while i < len(s):
        if s.startswith("\\begin{", i):
            env_depth += 1
        elif s.startswith("\\end{", i):
            env_depth -= 1
        c = s[i]
        if sep == "\\\\" and s.startswith("\\\\", i) and depth == 0 and env_depth == 0:
            parts.append("".join(buf))
            buf = []
            i += 2
            _, i = read_optional(s, i)
            continue
        if c == "\\":
            buf.append(s[i:i + 2])
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        if c == sep and depth == 0 and env_depth == 0:
            parts.append("".join(buf))
            buf = []
            i += 1
            continue
        buf.append(c)
        i += 1
    parts.append("".join(buf))
    return parts


def split_items(content: str) -> list[tuple[str | None, str]]:
    """Split list-environment content into (optional label, body) per top-level \\item."""
    items: list[tuple[str | None, str]] = []
    depth = env_depth = 0
    i, cur_start, cur_label = 0, None, None
    item_re = re.compile(r"\\item(?![A-Za-z])")
    while i < len(content):
        if content.startswith("\\begin{", i):
            env_depth += 1
        elif content.startswith("\\end{", i):
            env_depth -= 1
        c = content[i]
        if depth == 0 and env_depth == 0 and item_re.match(content, i):
            if cur_start is not None:
                items.append((cur_label, content[cur_start:i]))
            j = i + len("\\item")
            cur_label, j = read_optional(content, j)
            cur_start, i = j, j
            continue
        if c == "\\":
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        i += 1
    if cur_start is not None:
        items.append((cur_label, content[cur_start:]))
    return items


def collapse_ws(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()


def slugify(s: str, max_words: int = 4) -> str:
    words = re.findall(r"[a-z0-9]+", s.lower())
    return "-".join(words[:max_words]) or "block"


# ---------------------------------------------------------------------------
# Inputs: main.aux, refs.bib, numbers.json
# ---------------------------------------------------------------------------

@dataclass
class LabelInfo:
    number: str
    page: str
    title: str
    anchor: str

    @property
    def kind(self) -> str:
        return self.anchor.split(".", 1)[0].lower() if self.anchor else ""


def parse_aux(path: Path) -> dict[str, LabelInfo]:
    labels: dict[str, LabelInfo] = {}
    if not path.exists():
        return labels
    text = path.read_text(encoding="utf-8", errors="replace")
    for m in re.finditer(r"\\newlabel\{", text):
        try:
            key, j = read_group(text, m.end() - 1)
            grp, _ = read_group(text, skip_ws(text, j))
        except GenerationError:
            continue
        if key.endswith("@cref"):
            continue
        parts, k = [], 0
        while k < len(grp):
            if grp[k] == "{":
                c, k = read_group(grp, k)
                parts.append(c)
            else:
                k += 1
        parts += [""] * (4 - len(parts))
        labels[key] = LabelInfo(parts[0].strip(), parts[1], parts[2], parts[3])
    return labels


@dataclass
class BibEntry:
    kind: str
    key: str
    fields: dict[str, str]


def parse_bib(path: Path) -> list[BibEntry]:
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    entries = []
    for m in re.finditer(r"@(\w+)\s*\{", text):
        kind = m.group(1).lower()
        if kind in ("comment", "preamble", "string"):
            continue
        body, _ = read_group(text, m.end() - 1)
        key, _, rest = body.partition(",")
        fields: dict[str, str] = {}
        i = 0
        while i < len(rest):
            fm = re.compile(r"\s*([A-Za-z][\w-]*)\s*=\s*").match(rest, i)
            if not fm:
                i += 1
                continue
            name, i = fm.group(1).lower(), fm.end()
            if i < len(rest) and rest[i] == "{":
                val, i = read_group(rest, i)
            elif i < len(rest) and rest[i] == '"':
                j = i + 1
                while j < len(rest) and rest[j] != '"':
                    j = read_group(rest, j)[1] if rest[j] == "{" else j + 1
                val, i = rest[i + 1:j], j + 1
            else:
                vm = re.compile(r"[^,]*").match(rest, i)
                val, i = vm.group(0).strip(), vm.end()
            fields[name] = collapse_ws(val)
        entries.append(BibEntry(kind, key.strip(), fields))
    return entries


def _unbrace(s: str) -> str:
    return re.sub(r"[{}]", "", s).strip()


def bib_short_name(entry: BibEntry) -> str:
    raw = entry.fields.get("author") or entry.fields.get("editor") or ""
    authors = [a for a in split_bib_authors(raw) if a]
    lasts = []
    for a in authors:
        if a.startswith("{") and a.endswith("}") and read_group(a, 0)[1] == len(a):
            lasts.append(_unbrace(a))            # corporate author {Ecma International}
        elif "," in a:
            lasts.append(_unbrace(a.split(",", 1)[0]))
        else:
            lasts.append(_unbrace(a.split()[-1]))
    lasts = [latex_to_plain(x) for x in lasts]
    year = entry.fields.get("year", "n.d.")
    if not lasts:
        return f"{entry.key} {year}"
    if len(lasts) == 1:
        return f"{lasts[0]} {year}"
    if len(lasts) == 2:
        return f"{lasts[0]} & {lasts[1]} {year}"
    return f"{lasts[0]} et al. {year}"


def split_bib_authors(raw: str) -> list[str]:
    out, buf, depth = [], [], 0
    tokens = re.split(r"(\s+and\s+|[{}])", raw)
    for t in tokens:
        if t == "{":
            depth += 1
        elif t == "}":
            depth -= 1
        if depth == 0 and re.fullmatch(r"\s+and\s+", t or ""):
            out.append("".join(buf).strip())
            buf = []
        else:
            buf.append(t or "")
    out.append("".join(buf).strip())
    return out


def bib_reference_string(entry: BibEntry) -> str:
    f = entry.fields
    title = latex_to_plain(_unbrace(f.get("title", entry.key)))
    parts = []
    if f.get("journal"):
        s = latex_to_plain(_unbrace(f["journal"]))
        if f.get("volume"):
            s += " " + f["volume"]
            if f.get("number"):
                s += f"({f['number']})"
            if f.get("pages"):
                s += ":" + f["pages"].replace("--", "-")
        elif f.get("pages"):
            s += " " + f["pages"].replace("--", "-")
        parts.append(s)
    elif f.get("booktitle"):
        parts.append(latex_to_plain(_unbrace(f["booktitle"])) + (f" {f['year']}" if f.get("year") else ""))
    elif entry.kind == "techreport":
        parts.append(latex_to_plain(_unbrace(f.get("number") or f.get("institution", ""))))
    if f.get("note"):
        parts.append(latex_to_plain(_unbrace(f["note"])))
    m = re.search(r"arxiv\.org/abs/([\w.]+)", f.get("url", ""))
    if m and not any(m.group(1) in p for p in parts):
        parts.append(f"arXiv:{m.group(1)}")
    sep = " " if title.endswith(("?", "!", ".")) else ". "
    return title + (sep + ", ".join(p for p in parts if p) if any(parts) else "")


class Numbers:
    """Lazy numbers.json lookup for \\val{key}; any problem is a hard error naming the key."""

    def __init__(self, path: Path):
        self.path = path
        self._values: dict | None = None

    def get(self, key: str) -> str:
        if self._values is None:
            if not self.path.exists():
                raise GenerationError(f"\\val{{{key}}} is used but {self.path} does not exist")
            data = json.loads(self.path.read_text(encoding="utf-8"))
            values = data.get("values") if isinstance(data, dict) else None
            if not isinstance(values, dict):
                raise GenerationError(f"{self.path}: top-level 'values' object missing (needed for \\val{{{key}}})")
            self._values = values
        if key not in self._values:
            raise GenerationError(f"\\val{{{key}}}: key {key!r} not found in {self.path}")
        entry = self._values[key]
        value = entry.get("value") if isinstance(entry, dict) else entry
        if not isinstance(value, str) or not value:
            raise GenerationError(f"\\val{{{key}}}: {self.path.name} has no non-empty string 'value' for it")
        return value


# ---------------------------------------------------------------------------
# Inline LaTeX -> HTML
# ---------------------------------------------------------------------------

FORMAT_TAGS = {
    "emph": ("<em>", "</em>"), "textit": ("<em>", "</em>"), "textsl": ("<em>", "</em>"),
    "textbf": ("<strong>", "</strong>"), "texttt": ("<code>", "</code>"),
    "underline": ("<u>", "</u>"), "textsuperscript": ("<sup>", "</sup>"),
    "textsubscript": ("<sub>", "</sub>"),
    "textsc": ("", ""), "textsf": ("", ""), "textrm": ("", ""), "textup": ("", ""),
    "textnormal": ("", ""), "textmd": ("", ""), "mbox": ("", ""), "hbox": ("", ""),
    "text": ("", ""), "makebox": ("", ""),
}
TEXT_SYMBOLS = {
    "ldots": "...", "dots": "...", "textendash": "&ndash;", "textemdash": "&mdash;",
    "S": "§", "dag": "†", "textdagger": "†", "ddag": "‡", "textdaggerdbl": "‡",
    "LaTeX": "LaTeX", "TeX": "TeX", "textbackslash": "\\", "textasciitilde": "~",
    "textless": "&lt;", "textgreater": "&gt;", "textbar": "|", "copyright": "©",
    "textregistered": "®", "texttrademark": "™", "textdegree": "°", "newline": " ",
    "linebreak": " ", "quad": " ", "qquad": " ", "textquotedbl": '"',
}
IGNORED_NOARG = {
    "today", "centering", "raggedright", "raggedleft", "small", "normalsize", "footnotesize",
    "scriptsize", "tiny", "large", "Large", "LARGE", "huge", "Huge", "noindent", "par",
    "sloppy", "fussy", "protect", "relax", "hfill", "vfill", "maketitle", "clearpage",
    "newpage", "bigskip", "medskip", "smallskip", "toprule", "midrule", "bottomrule",
    "addlinespace", "hline", "appendix", "tableofcontents", "footnotemark", "normalfont",
    "bfseries", "itshape", "ttfamily", "rmfamily", "sffamily", "em", "bf", "it",
}
IGNORED_ONEARG = {"label", "vspace", "hspace", "input", "include", "bibliographystyle",
                  "bibliography", "color", "pagestyle", "thispagestyle", "phantomsection",
                  "addcontentsline"}
MATH_SYMBOLS = {
    "dagger": "†", "ddagger": "‡", "times": "x", "ll": "much less than", "gg": "much greater than",
    "sim": "~", "approx": "≈", "le": "≤", "leq": "≤", "ge": "≥", "geq": "≥", "neq": "≠",
    "ne": "≠", "pm": "±", "mp": "∓", "cdot": "·", "infty": "∞", "to": "→", "rightarrow": "→",
    "leftarrow": "←", "Rightarrow": "⇒", "ldots": "…", "dots": "…", "cdots": "…", "prime": "′",
    "in": "∈", "notin": "∉", "subset": "⊂", "cup": "∪", "cap": "∩", "sum": "Σ", "prod": "Π",
    "%": "%", "{": "{", "}": "}", "_": "_", "&": "&amp;", "#": "#", "$": "$",
    ",": " ", ";": " ", ":": " ", "!": "", " ": " ", "quad": " ", "qquad": " ",
    "left": "", "right": "", "big": "", "Big": "", "bigl": "", "bigr": "", "displaystyle": "",
    "lvert": "|", "rvert": "|", "mid": "|", "langle": "⟨", "rangle": "⟩",
}
GREEK = ("alpha beta gamma delta epsilon varepsilon zeta eta theta vartheta iota kappa lambda mu nu xi "
         "pi rho sigma tau upsilon phi varphi chi psi omega Gamma Delta Theta Lambda Xi Pi Sigma "
         "Upsilon Phi Psi Omega").split()
GREEK_CHARS = "αβγδεεζηθϑικλμνξπρστυφφχψωΓΔΘΛΞΠΣΥΦΨΩ"
MATH_SYMBOLS.update(dict(zip(GREEK, GREEK_CHARS)))
MATH_TEXTLIKE = {"text", "mathrm", "textrm", "mathit", "mathbf", "textbf", "operatorname",
                 "mathsf", "mathtt", "mbox", "textit", "mathcal", "boldsymbol", "bm"}
ACCENTS = {"'": "\u0301", "`": "\u0300", '"': "\u0308", "^": "\u0302", "~": "\u0303",
           "c": "\u0327", "v": "\u030c", "u": "\u0306", "=": "\u0304", ".": "\u0307", "H": "\u030b"}
REF_NAMES = {"section": "Section", "subsection": "Section", "subsubsection": "Section",
             "table": "Table", "figure": "Figure", "appendix": "Appendix",
             "equation": "Equation", "item": "item", "enumi": "item"}
INLINE_TRANSPARENT_ENVS = {"sloppypar", "center", "flushleft", "flushright", "quote",
                           "quotation", "small", "footnotesize", "minipage"}
MATH_ENVS = {"equation", "equation*", "align", "align*", "displaymath", "math", "gather",
             "gather*", "multline", "multline*"}


class Renderer:
    """Converts inline LaTeX to the DOC array's HTML conventions.

    `cite_mode` 'template' emits placeholders later serialized as ${cite(...)};
    'static' emits the rendered <cite> HTML (for plain-string table cells).
    Footnotes met while rendering are collected in `self.footnotes` (raw LaTeX).
    """

    def __init__(self, labels: dict[str, LabelInfo], cites: dict[str, str], numbers: Numbers,
                 warnings: list[str]):
        self.labels = labels
        self.cites = cites
        self.numbers = numbers
        self.warnings = warnings
        self.footnotes: list[str] = []
        self.cite_mode = "template"

    def warn(self, msg: str) -> None:
        if msg not in self.warnings:
            self.warnings.append(msg)

    # -- public ------------------------------------------------------------
    def render(self, s: str) -> str:
        return self._collapse(self._render(s))

    def render_static(self, s: str) -> str:
        prev, self.cite_mode = self.cite_mode, "static"
        try:
            return self.render(s)
        finally:
            self.cite_mode = prev

    @staticmethod
    def _collapse(s: str) -> str:
        return re.sub(r"[ \t\r\n]+", " ", s).strip()

    # -- text mode -----------------------------------------------------------
    def _render(self, s: str) -> str:
        out: list[str] = []
        i, n = 0, len(s)
        while i < n:
            c = s[i]
            if c == "\\":
                i = self._command(s, i, out)
            elif c == "$":
                if s.startswith("$$", i):
                    j = s.find("$$", i + 2)
                    if j == -1:
                        raise GenerationError(f"unterminated $$ at {s[i:i + 40]!r}")
                    out.append(self.render_math(s[i + 2:j]))
                    i = j + 2
                else:
                    j = i + 1
                    while j < n and s[j] != "$":
                        j += 2 if s[j] == "\\" else 1
                    if j >= n:
                        raise GenerationError(f"unterminated $ at {s[i:i + 40]!r}")
                    out.append(self.render_math(s[i + 1:j]))
                    i = j + 1
            elif c == "{":
                inner, i = read_group(s, i)
                out.append(self._render(inner))
            elif c == "}":
                i += 1
            elif c == "~":
                out.append(" ")
                i += 1
            elif c == "-":
                if s.startswith("---", i):
                    out.append("&mdash;")
                    i += 3
                elif s.startswith("--", i):
                    out.append("&ndash;")
                    i += 2
                else:
                    out.append("-")
                    i += 1
            elif c == "`":
                if s.startswith("``", i):
                    out.append('"')
                    i += 2
                else:
                    out.append("'")
                    i += 1
            elif c == "'" and s.startswith("''", i):
                out.append('"')
                i += 2
            elif c == "<":
                out.append("&lt;")
                i += 1
            elif c == ">":
                out.append("&gt;")
                i += 1
            elif c == "&":
                out.append("&amp;")
                i += 1
            else:
                out.append(c)
                i += 1
        return "".join(out)

    def _command(self, s: str, i: int, out: list[str]) -> int:
        n = len(s)
        if i + 1 >= n:
            return n
        nxt = s[i + 1]
        if nxt == "\\":                                   # line break \\[..]
            out.append(" ")
            _, j = read_optional(s, i + 2)
            return j
        if not nxt.isalpha():                            # control symbol
            if nxt in ACCENTS and i + 2 < n:
                base, j = read_arg(s, i + 2)
                out.append(unicodedata.normalize("NFC", _unbrace(base)[:1] + ACCENTS[nxt] + _unbrace(base)[1:]))
                return j
            out.append({"%": "%", "_": "_", "&": "&amp;", "#": "#", "$": "$", "{": "{", "}": "}",
                        " ": " ", "\n": " ", ",": " ", ";": " ", "-": "", "@": "", "/": "",
                        "!": "", "(": "", ")": ""}.get(nxt, nxt))
            if nxt == "(":                                # \( ... \) inline math
                j = s.find("\\)", i + 2)
                if j == -1:
                    raise GenerationError("unterminated \\(")
                out.append(self.render_math(s[i + 2:j]))
                return j + 2
            return i + 2
        m = re.compile(r"[A-Za-z]+\*?").match(s, i + 1)
        name, j = m.group(0), m.end()
        base = name.rstrip("*")
        if base in FORMAT_TAGS:
            arg, j = read_arg(s, j)
            open_, close = FORMAT_TAGS[base]
            out.append(open_ + self._render(arg) + close)
            return j
        if base in TEXT_SYMBOLS:
            out.append(TEXT_SYMBOLS[base])
            return self._eat_space(s, j)
        if base in IGNORED_NOARG:
            return self._eat_space(s, j)
        if base in IGNORED_ONEARG:
            _, j = read_optional(s, j)
            _, j = read_arg(s, j)
            return j
        if base == "begin":
            env, j = read_group(s, j)
            end_start, end_end = find_env_end(s, j, env)
            out.append(self._render_env(env, s[j:end_start]))
            return end_end
        if base == "end":                                 # stray \end{..}
            _, j = read_group(s, j)
            return j
        if base == "item":
            label, j = read_optional(s, j)
            out.append(" " + (f"<strong>{self._render(label)}</strong>:" if label else ""))
            return j
        if base == "footnote":
            _, j = read_optional(s, j)
            arg, j = read_arg(s, j)
            self.footnotes.append(arg)
            return j
        if base in ("todo", "pending"):
            arg, j = read_arg(s, j)
            out.append(f'<span class="editorial-flag">[{base.upper()}: {self.render(arg)}]</span>')
            return j
        if base in ("url", "nolinkurl"):
            arg, j = read_arg(s, j)
            out.append(htmllib.escape(arg, quote=False))
            return j
        if base == "href":
            _, j = read_arg(s, j)
            arg, j = read_arg(s, j)
            out.append(self._render(arg))
            return j
        if base in ("ref", "pageref", "eqref", "Cref", "cref", "autoref", "Autoref", "vref"):
            arg, j = read_arg(s, j)
            out.append(self._ref(base, arg))
            return j
        if base in ("cite", "citep", "citet", "citealp", "citealt", "parencite", "textcite",
                    "citeauthor", "citeyear", "autocite"):
            _, j = read_optional(s, j)
            _, j = read_optional(s, j)
            arg, j = read_arg(s, j)
            out.append(self._cite([k.strip() for k in arg.split(",") if k.strip()]))
            return j
        if base == "val":
            arg, j = read_arg(s, j)
            out.append(self._render(self.numbers.get(arg.strip())))
            return j
        if base == "claim":
            _, j = read_arg(s, j)
            arg, j = read_arg(s, j)
            out.append(self._render(arg))
            return j
        if base == "multirow":
            _, j = read_arg(s, j)
            _, j = read_optional(s, j)
            _, j = read_arg(s, j)
            arg, j = read_arg(s, j)
            out.append(self._render(arg))
            return j
        if base == "multicolumn":
            _, j = read_arg(s, j)
            _, j = read_arg(s, j)
            arg, j = read_arg(s, j)
            out.append(self._render(arg))
            return j
        if base == "textcolor":
            _, j = read_optional(s, j)
            _, j = read_arg(s, j)
            arg, j = read_arg(s, j)
            out.append(self._render(arg))
            return j
        if base in ("paragraph", "subparagraph"):
            _, j = read_optional(s, j)
            arg, j = read_arg(s, j)
            out.append(f"<strong>{self._render(arg)}</strong>")
            return j
        if base in ("cmidrule",):
            k = skip_ws(s, j, newlines=False)
            if k < len(s) and s[k] == "(":
                j = s.index(")", k) + 1
            _, j = read_arg(s, j)
            return j
        # Unknown macro: render its brace arguments' text.
        self.warn(f"unknown macro \\{name} (rendered its arguments' text)")
        k = j
        while True:
            k2 = skip_ws(s, k, newlines=False)
            if k2 < len(s) and s[k2] == "{":
                arg, k = read_group(s, k2)
                out.append(self._render(arg))
            else:
                break
        return k if k != j else self._eat_space(s, j)

    @staticmethod
    def _eat_space(s: str, j: int) -> int:
        """TeX drops spaces after a control word; keep one if a newline-free gap follows text."""
        k = j
        while k < len(s) and s[k] in " \t":
            k += 1
        if k < len(s) and s[k] == "\n":
            k += 1
            while k < len(s) and s[k] in " \t":
                k += 1
        return k

    def _render_env(self, env: str, body: str) -> str:
        base = env.rstrip("*")
        if env in MATH_ENVS or base in MATH_ENVS:
            return " " + self.render_math(body) + " "
        if env in ("itemize", "enumerate", "description"):
            parts = []
            for n, (label, item) in enumerate(split_items(body), 1):
                txt = self.render(item)
                if env == "description" and label is not None:
                    parts.append(f"<strong>{self.render(label)}</strong>: {txt}")
                elif env == "enumerate":
                    parts.append(f"({n}) {txt}")
                else:
                    parts.append(txt)
            return " " + " ".join(parts) + " "
        if env in INLINE_TRANSPARENT_ENVS:
            return self._render(body)
        if env in ("tabular", "tabular*", "tikzpicture"):
            self.warn(f"\\begin{{{env}}} inside a paragraph was skipped")
            return ""
        self.warn(f"unknown environment {env} rendered as plain text")
        return self._render(body)

    def _ref(self, kind: str, arg: str) -> str:
        outs = []
        for key in [k.strip() for k in arg.split(",") if k.strip()]:
            info = self.labels.get(key)
            if info is None:
                self.warn(f"unresolved reference \\{kind}{{{key}}} (not in main.aux; rendered '??')")
                outs.append("??")
                continue
            if kind == "pageref":
                outs.append(info.page)
            elif kind == "eqref":
                outs.append(f"({info.number})")
            elif kind in ("Cref", "cref", "autoref", "Autoref", "vref"):
                name = REF_NAMES.get(info.kind, "")
                if kind == "cref":
                    name = name.lower()
                outs.append(f"{name} {info.number}".strip())
            else:
                outs.append(info.number)
        return ", ".join(outs)

    def _cite(self, keys: list[str]) -> str:
        for k in keys:
            if k not in self.cites:
                self.warn(f"citation key {k!r} not found in refs.bib")
        if self.cite_mode == "static":
            names = "; ".join(htmllib.escape(self.cites.get(k, k), quote=False) for k in keys)
            return f' <cite contenteditable="false">({names})</cite>'
        return CITE_OPEN + ",".join(keys) + CITE_CLOSE

    # -- math mode -----------------------------------------------------------
    def render_math(self, m: str) -> str:
        out: list[str] = []
        i, n = 0, len(m)
        while i < n:
            c = m[i]
            if c == "\\":
                if i + 1 < n and not m[i + 1].isalpha():
                    out.append(MATH_SYMBOLS.get(m[i + 1], m[i + 1]))
                    i += 2
                    continue
                mm = re.compile(r"[A-Za-z]+").match(m, i + 1)
                name, j = mm.group(0), mm.end()
                if name in MATH_TEXTLIKE:
                    arg, j = read_arg(m, j)
                    out.append(self._render(arg) if name in ("text", "textrm", "mbox", "textit", "textbf")
                               else self.render_math(arg))
                elif name == "frac":
                    a, j = read_arg(m, j)
                    b, j = read_arg(m, j)
                    out.append(f"{self.render_math(a)}/{self.render_math(b)}")
                elif name == "sqrt":
                    a, j = read_arg(m, j)
                    out.append(f"√({self.render_math(a)})")
                elif name in MATH_SYMBOLS:
                    out.append(MATH_SYMBOLS[name])
                elif name in ("val", "ref", "claim", "cite", "citep"):
                    sub: list[str] = []
                    j = self._command(m, i, sub)
                    out.append("".join(sub))
                else:
                    self.warn(f"unknown math macro \\{name} (rendered as its name)")
                    out.append(name)
                i = j
            elif c in "^_":
                arg, j = read_arg(m, i + 1)
                if arg.startswith("\\") and arg[1:] in MATH_TEXTLIKE | {"frac", "sqrt"}:
                    # x_\text{eff}: the macro token takes the following group(s) with it
                    for _ in range(2 if arg[1:] == "frac" else 1):
                        g, j = read_arg(m, j)
                        arg += "{" + g + "}"
                inner = arg.strip()
                if c == "^" and inner in ("\\dagger", "\\ddagger"):
                    out.append(MATH_SYMBOLS[inner[1:]])
                elif c == "^" and inner in ("\\prime", "'"):
                    out.append("′")
                elif c == "^":
                    out.append(f"<sup>{self.render_math(arg)}</sup>")
                else:
                    out.append("_" + self.render_math(arg))
                i = j
            elif c == "{":
                inner, i = read_group(m, i)
                out.append(self.render_math(inner))
            elif c == "}":
                i += 1
            elif c == "<":
                out.append("&lt;")
                i += 1
            elif c == ">":
                out.append("&gt;")
                i += 1
            elif c == "&":
                out.append("&amp;")
                i += 1
            elif c == "~":
                out.append(" ")
                i += 1
            elif c in " \t\r\n":
                if out and not out[-1].endswith(" "):
                    out.append(" ")
                i += 1
            else:
                out.append(c)
                i += 1
        return "".join(out).strip()


def latex_to_plain(s: str) -> str:
    """Best-effort plain text for bib fields and headers (no refs/cites needed)."""
    r = Renderer({}, {}, Numbers(Path("numbers.json")), [])
    return html_to_plain(r.render_static(s))


def html_to_plain(s: str) -> str:
    s = re.sub(r"<[^>]+>", "", s)
    return collapse_ws(htmllib.unescape(s))


def cites_to_template(s: str) -> str:
    return re.sub(CITE_OPEN + r"([^" + CITE_CLOSE + r"]*)" + CITE_CLOSE,
                  lambda m: "${cite(" + ",".join(f"'{k}'" for k in m.group(1).split(",")) + ")}", s)


# ---------------------------------------------------------------------------
# Document model
# ---------------------------------------------------------------------------

@dataclass(eq=False)
class Block:
    kind: str                       # 'para' | 'footnote' | 'table' | 'figure' | 'hand'
    section: str
    tex: str | None = None
    text: str | None = None         # HTML with cite placeholders
    h2: str | None = None
    h3: str | None = None
    label: str | None = None
    caption: str | None = None
    headers: list | None = None
    rows: list | None = None
    img: str | None = None
    latex_label: str | None = None
    parent: "Block | None" = None
    id_base: str = ""
    id_numbered: bool = False
    id: str | None = None
    raw: str | None = None          # verbatim source (hand-authored blocks)
    old: "OldBlock | None" = None
    match: str = ""                 # '' | 'in-order' | 'moved'
    sim: float = 0.0

    @property
    def doc_type(self) -> str:
        return self.kind if self.kind in ("table", "figure") else "para"


@dataclass
class HeaderGroup:
    level: str                      # 'h2' | 'h3'
    text: str
    section: str
    blocks: list[Block] = field(default_factory=list)
    claimed: bool = False


@dataclass
class Generated:
    blocks: list[Block]
    headers: list[HeaderGroup]
    sections: list[dict]
    cites: dict[str, str]
    bib: list[BibEntry]
    warnings: list[str]


class DocBuilder:
    def __init__(self, tex_path: Path, aux_path: Path, bib_path: Path, numbers_path: Path,
                 old: "OldDoc | None" = None):
        self.tex_path = tex_path
        self.warnings: list[str] = []
        self.labels = parse_aux(aux_path)
        if not aux_path.exists():
            self.warnings.append(f"{aux_path} not found: every \\ref renders '??' (build the paper first)")
        elif tex_path.exists() and tex_path.stat().st_mtime > aux_path.stat().st_mtime + 1:
            self.warnings.append("main.aux is older than main.tex: \\ref numbers may be stale "
                                 "(rebuild the paper, e.g. paper/build.ps1)")
        self.bib = parse_bib(bib_path)
        self.cites = {e.key: bib_short_name(e) for e in self.bib}
        self.numbers = Numbers(numbers_path)
        self.r = Renderer(self.labels, self.cites, self.numbers, self.warnings)
        self.old = old
        self.blocks: list[Block] = []
        self.headers: list[HeaderGroup] = []
        self.sections: list[dict] = []
        self.section = ABSTRACT_SECTION[0]
        self.sub_base: str | None = None
        self.h2_group: HeaderGroup | None = None
        self.h3_group: HeaderGroup | None = None
        self.in_appendix = False
        self.table_blocks: dict[str, Block] = {}
        self.relocated: dict[str, list[Block]] = {}

    # -- entry point ---------------------------------------------------------
    def build(self) -> Generated:
        src = self.tex_path.read_text(encoding="utf-8")
        src = self._inline_inputs(strip_comments(src), self.tex_path.parent, 0)
        b = src.find("\\begin{document}")
        e = src.rfind("\\end{document}")
        body = src[b + len("\\begin{document}"):e if e != -1 else len(src)] if b != -1 else src
        self._scan(body)
        self._place_relocated()
        return Generated(self.blocks, self.headers, self.sections, self.cites, self.bib, self.warnings)

    def _inline_inputs(self, s: str, base: Path, depth: int) -> str:
        if depth > 5:
            return s

        def repl(m: re.Match) -> str:
            name = m.group(2).strip()
            p = base / (name if name.endswith(".tex") else name + ".tex")
            if not p.exists():
                return m.group(0)
            return self._inline_inputs(strip_comments(p.read_text(encoding="utf-8")), p.parent, depth + 1)
        return re.sub(r"\\(input|include)\{([^}]*)\}", repl, s)

    # -- top-level scanner ---------------------------------------------------
    def _scan(self, body: str) -> None:
        buf: list[str] = []
        i, n, depth = 0, len(body), 0

        def flush() -> None:
            raw = "".join(buf)
            buf.clear()
            if raw.strip():
                self._paragraph(raw)

        sec_re = re.compile(r"\\(section|subsection|subsubsection)(\*?)(?![A-Za-z])")
        while i < n:
            c = body[i]
            if depth == 0 and c == "\n":
                m = re.compile(r"\n[ \t]*\n\s*").match(body, i)
                if m:
                    flush()
                    i = m.end()
                    continue
            if c == "\\" and depth == 0:
                m = sec_re.match(body, i)
                if m:
                    flush()
                    j = m.end()
                    _, j = read_optional(body, j)
                    title, j = read_arg(body, j)
                    label = None
                    k = skip_ws(body, j)
                    if body.startswith("\\label{", k):
                        label, j = read_group(body, k + len("\\label"))
                    self._heading(m.group(1), title, label)
                    i = j
                    continue
                m = re.compile(r"\\begin\{([^}]*)\}").match(body, i)
                if m:
                    env = m.group(1)
                    if env in INLINE_TRANSPARENT_ENVS:
                        i = m.end()
                        continue
                    end_start, end_end = find_env_end(body, m.end(), env)
                    content = body[m.end():end_start]
                    if env.rstrip("*") in ("table", "figure"):
                        flush()
                        self._float(env.rstrip("*"), content)
                    elif env == "abstract":
                        flush()
                        self._abstract(content)
                    elif (env == "enumerate" and self.section in ENUM_SPLIT_LEADS) or \
                            (env == "description" and self.in_appendix):
                        flush()
                        self._split_list(env, content)
                    else:
                        buf.append(body[i:end_end])
                    i = end_end
                    continue
                m = re.compile(r"\\end\{([^}]*)\}").match(body, i)
                if m and m.group(1) in INLINE_TRANSPARENT_ENVS:
                    i = m.end()
                    continue
                if body.startswith("\\appendix", i) and not body[i + 9:i + 10].isalpha():
                    flush()
                    self.in_appendix = True
                    i += len("\\appendix")
                    continue
                m = re.compile(r"\\bibliography\{([^}]*)\}").match(body, i)
                if m:
                    flush()
                    self._references()
                    i = m.end()
                    continue
                m = re.compile(r"\\(maketitle|bibliographystyle\{[^}]*\}|clearpage|newpage)").match(body, i)
                if m:
                    i = m.end()
                    continue
                buf.append(body[i:i + 2])
                i += 2
                continue
            if c == "\\":
                buf.append(body[i:i + 2])
                i += 2
                continue
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            buf.append(c)
            i += 1
        flush()

    # -- structure handlers -------------------------------------------------
    def _heading(self, level: str, title: str, label: str | None) -> None:
        plain = html_to_plain(self.r.render_static(title))
        if level == "section":
            info = self.labels.get(label or "")
            if self.in_appendix:
                num = info.number if info else ""
                plain = f"Appendix {num}: {plain}" if num else f"Appendix: {plain}"
            self.section = self._resolve_section(plain, label)
            self.sub_base = None
            self.h2_group = HeaderGroup("h2", plain, self.section)
            self.h3_group = None
            self.headers.append(self.h2_group)
        else:
            suffix = label.split(":", 1)[1] if label and ":" in label else slugify(plain, 3)
            suffix = slugify(suffix, 6)
            self.sub_base = suffix if suffix.startswith(self.section + "-") else f"{self.section}-{suffix}"
            self.h3_group = HeaderGroup("h3", plain, self.section)
            self.headers.append(self.h3_group)

    def _resolve_section(self, title: str, label: str | None) -> str:
        old_sections = self.old.sections if self.old else []
        old_ids = {s["id"]: s["label"] for s in old_sections}
        suffix = label.split(":", 1)[1] if label and ":" in label else None
        sid = None
        if suffix and suffix in old_ids:
            sid = suffix
        elif self.old:
            for ob in self.old.blocks:
                if ob.data.get("h2") == title and ob.data.get("section"):
                    sid = ob.data["section"]
                    break
        if sid is None:
            base = slugify(suffix or title, 4)
            if self.in_appendix and not base.startswith("appendix"):
                base = "appendix-" + base
            sid, k = base, 2
            while any(s["id"] == sid for s in self.sections):
                sid, k = f"{base}-{k}", k + 1
        if not any(s["id"] == sid for s in self.sections):
            self.sections.append({"id": sid, "label": old_ids.get(sid, title)})
        return sid

    def _add(self, block: Block) -> Block:
        """Append a main block (plus its footnote blocks) and register it with header groups."""
        self.blocks.append(block)
        if block.kind != "footnote":
            for g in (self.h2_group, self.h3_group):
                if g is not None:
                    g.blocks.append(block)
        pending = list(self.r.footnotes)
        self.r.footnotes.clear()
        while pending:
            raw = pending.pop(0)
            fn = Block("footnote", self.section, parent=block)
            fn.tex = "[footnote] " + collapse_ws(raw)
            fn.text = f'<span class="footnote-block">Footnote: {self.r.render(raw)}</span>'
            pending.extend(self.r.footnotes)
            self.r.footnotes.clear()
            self.blocks.append(fn)
        return block

    def _para_block(self, raw_tex: str, text: str) -> Block:
        b = Block("para", self.section, tex=collapse_ws(raw_tex), text=text)
        if self.sub_base:
            b.id_base, b.id_numbered = self.sub_base, False
        else:
            b.id_base, b.id_numbered = self.section, True
        return b

    def _paragraph(self, raw: str) -> None:
        self.r.footnotes.clear()
        text = self.r.render(raw)
        if not html_to_plain(text) and not self.r.footnotes:
            return
        self._add(self._para_block(raw, text))

    def _abstract(self, content: str) -> None:
        self._ensure_front_section()
        for k, chunk in enumerate(re.split(r"\n[ \t]*\n", content)):
            if not chunk.strip():
                continue
            self.r.footnotes.clear()
            b = Block("para", self.section, tex=collapse_ws(chunk), text=self.r.render(chunk))
            b.id_base, b.id_numbered = "abstract", False
            if k == 0:
                g = HeaderGroup("h2", "Abstract", self.section)
                self.headers.append(g)
                self.h2_group = g
            self._add(b)
        self.h2_group = None

    def _ensure_front_section(self) -> None:
        sid, label = ABSTRACT_SECTION
        if self.old:
            for ob in self.old.blocks:
                if ob.data.get("h2") == "Abstract" and ob.data.get("section"):
                    sid = ob.data["section"]
            label = {s["id"]: s["label"] for s in self.old.sections}.get(sid, label)
        self.section = sid
        if not any(s["id"] == sid for s in self.sections):
            self.sections.append({"id": sid, "label": label})

    def _split_list(self, env: str, content: str) -> None:
        for n, (label, body) in enumerate(split_items(content), 1):
            self.r.footnotes.clear()
            if env == "enumerate":
                lead = ENUM_SPLIT_LEADS[self.section].format(n=n)
                stripped = body.lstrip()
                if stripped.startswith("\\textbf{"):
                    inner, j = read_group(stripped, len("\\textbf"))
                    text = self.r.render("\\textbf{" + lead + inner + "}" + stripped[j:])
                else:
                    text = f"<strong>{htmllib.escape(lead.strip())}</strong> " + self.r.render(body)
                b = Block("para", self.section, tex=collapse_ws(body), text=text)
                b.id_base, b.id_numbered = (self.section[:-1] if self.section.endswith("s") else self.section), True
                self._add(b)
                continue
            # description item in the appendix: relocate beside the referenced table
            label_html = self.r.render(label or "")
            body_html = self.r.render(body)
            raw_item = collapse_ws(f"\\item[{label}] {body}" if label is not None else f"\\item {body}")
            tab = re.search(r"\\ref\{(tab:[^}]+)\}", label or "")
            if tab and tab.group(1) in self.table_blocks:
                note = Block("footnote", self.section)
                note.tex = "[appendix note] " + raw_item
                note.text = (f'<span class="footnote-block">Footnote: <strong>{label_html}</strong>: '
                             f"{body_html}</span>")
                note.latex_label = tab.group(1)
                if self.r.footnotes:
                    self.r.warn("\\footnote inside an appendix note was dropped")
                self.r.footnotes.clear()
                self.relocated.setdefault(tab.group(1), []).append(note)
                continue
            text = (f"<strong>{label_html}</strong>: {body_html}" if label is not None else body_html)
            self._add(self._para_block(raw_item, text))

    def _place_relocated(self) -> None:
        for tab_label, notes in self.relocated.items():
            table = self.table_blocks[tab_label]
            idx = self.blocks.index(table) + 1
            while idx < len(self.blocks) and self.blocks[idx].kind == "footnote" and self.blocks[idx].parent is table:
                idx += 1
            for note in notes:
                note.parent = table
                note.section = table.section
                self.blocks.insert(idx, note)
                idx += 1

    def _float(self, kind: str, content: str) -> None:
        cap_raw, label = "", None
        m = re.search(r"\\caption(?![A-Za-z])", content)
        if m:
            _, j = read_optional(content, m.end())
            cap_raw, _ = read_arg(content, j)
        m = re.search(r"\\label\{([^}]*)\}", content)
        if m:
            label = m.group(1)
        info = self.labels.get(label or "")
        name = "Table" if kind == "table" else "Figure"
        if label and info is None:
            self.r.warn(f"unresolved {kind} label {label!r} (not in main.aux; labelled '{name} ??')")
        self.r.footnotes.clear()
        b = Block(kind, self.section, label=f"{name} {info.number if info else '??'}",
                  caption=self.r.render(cap_raw), latex_label=label)
        b.id_base = ("tab-" if kind == "table" else "fig-") + slugify(
            (label.split(":", 1)[1] if label and ":" in label else label) or name, 8)
        if kind == "table":
            b.headers, b.rows = self._tabular(content)
            if label:
                self.table_blocks[label] = b
        self._add(b)

    def _tabular(self, content: str) -> tuple[list, list]:
        m = re.search(r"\\begin\{(tabular\*?|tabularx)\}", content)
        if not m:
            self.r.warn("table without a tabular environment")
            return [], []
        j = m.end()
        if m.group(1) != "tabular":
            _, j = read_arg(content, j)              # width
        _, j = read_optional(content, j)
        _, j = read_arg(content, j)                  # column spec
        end_start, _ = find_env_end(content, j, m.group(1))
        body = content[j:end_start]
        rule_re = re.compile(r"\s*\\(toprule|midrule|bottomrule|hline|addlinespace|cmidrule|specialrule)"
                             r"(?![A-Za-z])")
        headers: list[str] | None = None
        rows: list[list[str]] = []
        group_label = ""
        for chunk in split_top_level(body, "\\\\"):
            new_group = False
            while True:
                mm = rule_re.match(chunk)
                if not mm:
                    break
                k = mm.end()
                if mm.group(1) == "cmidrule":
                    k2 = skip_ws(chunk, k, newlines=False)
                    if k2 < len(chunk) and chunk[k2] == "(":
                        k = chunk.index(")", k2) + 1
                    _, k = read_arg(chunk, k)
                elif mm.group(1) == "specialrule":
                    for _ in range(3):
                        _, k = read_arg(chunk, k)
                else:
                    _, k = read_optional(chunk, k)
                if mm.group(1) in ("midrule", "addlinespace", "hline", "cmidrule"):
                    new_group = True
                chunk = chunk[k:]
            if not chunk.strip():
                continue
            cells = [self.r.render_static(c) for c in split_top_level(chunk, "&")]
            if headers is None:
                headers = cells
                continue
            if new_group:
                group_label = ""
            if cells and cells[0] == "" and group_label:
                cells[0] = group_label
            elif cells and cells[0]:
                group_label = cells[0]
            rows.append(cells)
        return headers or [], rows

    def _references(self) -> None:
        if not self.bib:
            return
        b = Block("table", self.section, label="refs.bib", caption=REFS_TABLE_CAPTION)
        b.headers = ["Cited as", "Reference"]
        b.rows = [[self.cites[e.key], bib_reference_string(e)] for e in self.bib]
        b.id_base = REFS_TABLE_ID
        self._add(b)


# ---------------------------------------------------------------------------
# Reading the current DOC out of margin_notes.html (small JS-literal parser)
# ---------------------------------------------------------------------------

class JSParser:
    IDENT = re.compile(r"[A-Za-z_$][\w$]*")
    NUMBER = re.compile(r"-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?")

    def __init__(self, src: str, pos: int):
        self.src, self.pos = src, pos

    def ws(self) -> None:
        s = self.src
        while self.pos < len(s):
            if s[self.pos] in " \t\r\n":
                self.pos += 1
            elif s.startswith("//", self.pos):
                j = s.find("\n", self.pos)
                self.pos = len(s) if j == -1 else j + 1
            elif s.startswith("/*", self.pos):
                self.pos = s.index("*/", self.pos) + 2
            else:
                break

    def value(self):
        self.ws()
        c = self.src[self.pos]
        if c == "{":
            return self.obj()
        if c == "[":
            return self.arr()[0]
        if c in "'\"":
            return self.string(c)
        if c == "`":
            return self.template()
        m = self.NUMBER.match(self.src, self.pos)
        if m:
            self.pos = m.end()
            return float(m.group(0)) if "." in m.group(0) else int(m.group(0))
        m = self.IDENT.match(self.src, self.pos)
        if m and m.group(0) in ("true", "false", "null", "undefined"):
            self.pos = m.end()
            return {"true": True, "false": False}.get(m.group(0))
        raise GenerationError(f"unsupported JS syntax at {self.src[self.pos:self.pos + 40]!r}")

    def obj(self) -> dict:
        self.pos += 1
        d = {}
        while True:
            self.ws()
            if self.src[self.pos] == "}":
                self.pos += 1
                return d
            c = self.src[self.pos]
            if c in "'\"":
                key = self.string(c)
            else:
                m = self.IDENT.match(self.src, self.pos)
                if not m:
                    raise GenerationError(f"bad object key at {self.src[self.pos:self.pos + 40]!r}")
                key, self.pos = m.group(0), m.end()
            self.ws()
            if self.src[self.pos] != ":":
                raise GenerationError(f"expected ':' at {self.src[self.pos:self.pos + 40]!r}")
            self.pos += 1
            d[key] = self.value()
            self.ws()
            if self.src[self.pos] == ",":
                self.pos += 1

    def arr(self) -> tuple[list, list[tuple[int, int]]]:
        self.pos += 1
        items, spans = [], []
        while True:
            self.ws()
            if self.src[self.pos] == "]":
                self.pos += 1
                return items, spans
            start = self.pos
            items.append(self.value())
            spans.append((start, self.pos))
            self.ws()
            if self.src[self.pos] == ",":
                self.pos += 1

    def _escape(self) -> str:
        s, p = self.src, self.pos
        c = s[p + 1]
        simple = {"n": "\n", "t": "\t", "r": "\r", "b": "\b", "f": "\f", "v": "\v", "0": "\0"}
        if c in simple:
            self.pos += 2
            return simple[c]
        if c == "x":
            self.pos += 4
            return chr(int(s[p + 2:p + 4], 16))
        if c == "u":
            if s[p + 2] == "{":
                j = s.index("}", p)
                self.pos = j + 1
                return chr(int(s[p + 3:j], 16))
            self.pos += 6
            return chr(int(s[p + 2:p + 6], 16))
        if c == "\r" and s[p + 2:p + 3] == "\n":
            self.pos += 3
            return ""
        if c in "\n\r":
            self.pos += 2
            return ""
        self.pos += 2
        return c

    def string(self, q: str) -> str:
        self.pos += 1
        out = []
        while True:
            c = self.src[self.pos]
            if c == "\\":
                out.append(self._escape())
            elif c == q:
                self.pos += 1
                return "".join(out)
            else:
                out.append(c)
                self.pos += 1

    def template(self) -> str:
        """Template literal; ${...} substitutions are kept verbatim in the result."""
        self.pos += 1
        out = []
        s = self.src
        while True:
            c = s[self.pos]
            if c == "\\":
                out.append(self._escape())
            elif c == "`":
                self.pos += 1
                return "".join(out)
            elif s.startswith("${", self.pos):
                start, depth, j = self.pos, 0, self.pos + 1
                while True:
                    ch = s[j]
                    if ch in "'\"`":
                        sub = JSParser(s, j)
                        sub.value()
                        j = sub.pos
                        continue
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            break
                    j += 1
                out.append(s[start:j + 1])
                self.pos = j + 1
            else:
                out.append(c)
                self.pos += 1


@dataclass(eq=False)
class OldBlock:
    index: int
    data: dict
    raw: str

    @property
    def id(self) -> str:
        return self.data.get("id", "")

    @property
    def kind(self) -> str:
        t = self.data.get("type")
        if t in ("table", "figure"):
            return t
        if "footnote-block" in (self.data.get("text") or "") or (self.data.get("tex") or "").startswith("["):
            return "footnote"
        return "para"

    @property
    def doc_type(self) -> str:
        return self.kind if self.kind in ("table", "figure") else "para"


@dataclass
class OldDoc:
    html: str
    region_start: int
    region_end: int
    has_markers: bool
    cites: dict
    sections: list[dict]
    blocks: list[OldBlock]
    retired: list[str]

    def by_id(self) -> dict[str, OldBlock]:
        return {b.id: b for b in self.blocks}


def _locate(html: str, needle: str, start: int = 0, end: int | None = None) -> int:
    idx = html.find(needle, start, end if end is not None else len(html))
    if idx == -1:
        raise GenerationError(f"{needle!r} not found in margin_notes.html")
    return idx


def parse_old_doc(html: str) -> OldDoc:
    begin = html.find(BEGIN_MARKER)
    end_marker = html.find("\n" + END_MARKER, begin if begin != -1 else 0)
    has_markers = begin != -1 and end_marker != -1
    if (begin == -1) != (end_marker == -1):
        raise GenerationError("only one of the BEGIN/END GENERATED markers is present in margin_notes.html")
    lo = begin if has_markers else 0
    cites_at = _locate(html, "const CITES = {", lo)
    p = JSParser(html, cites_at + len("const CITES = "))
    cites = p.obj()
    sec_at = _locate(html, "const SECTIONS = [", p.pos)
    p = JSParser(html, sec_at + len("const SECTIONS = "))
    sections, _ = p.arr()
    doc_at = _locate(html, "const DOC = [", p.pos)
    p = JSParser(html, doc_at + len("const DOC = "))
    items, spans = p.arr()
    if html[p.pos:p.pos + 1] != ";":
        raise GenerationError("expected ';' after the DOC array")
    doc_end = p.pos + 1
    retired: list[str] = []
    region_start = begin if has_markers else cites_at
    region_end = end_marker + 1 + len(END_MARKER) if has_markers else doc_end
    m = re.search(re.escape(RETIRED_PREFIX) + r"(.*)", html[region_start:region_end])
    if m:
        retired = [x.strip() for x in m.group(1).split(",") if x.strip()]
    blocks = [OldBlock(i, d, html[a:b]) for i, (d, (a, b)) in enumerate(zip(items, spans))]
    if not has_markers and html[region_start - 1:region_start] not in ("\n", ""):
        raise GenerationError("'const CITES = {' must start a line for first-run marker insertion")
    return OldDoc(html, region_start, region_end, has_markers, cites, sections, blocks, retired)


# ---------------------------------------------------------------------------
# Similarity + alignment
# ---------------------------------------------------------------------------

_TPL_CITE_RE = re.compile(r"\$\{cite\(([^)]*)\)\}")


@functools.lru_cache(maxsize=None)
def norm_plain(s: str | None) -> str:
    s = cites_to_template(s or "")
    s = _TPL_CITE_RE.sub(lambda m: " [cite:" + ",".join(k.strip().strip("'\"") for k in m.group(1).split(",")) + "] ", s)
    return html_to_plain(s)


def block_compare_text(d: dict) -> str:
    """Plain text used for similarity: text for paragraphs; caption (+cells) for floats."""
    if d.get("type") == "table":
        cells = " || ".join(" | ".join(norm_plain(c) for c in r) for r in (d.get("rows") or []))
        return f"{norm_plain(d.get('caption'))} || {' | '.join(norm_plain(h) for h in d.get('headers') or [])} || {cells}"
    if d.get("type") == "figure":
        return norm_plain(d.get("caption"))
    return norm_plain(d.get("text"))


def gen_dict(b: Block) -> dict:
    d = {"id": b.id, "section": b.section}
    if b.kind == "table":
        d.update(type="table", label=b.label, caption=b.caption, headers=b.headers, rows=b.rows)
    elif b.kind == "figure":
        d.update(type="figure", label=b.label, caption=b.caption)
    else:
        d.update(tex=b.tex, text=b.text)
    return d


@functools.lru_cache(maxsize=None)
def _words_and_shingles(s: str) -> tuple[tuple[str, ...], frozenset]:
    words = tuple(s.split())
    if len(words) < 3:
        return words, frozenset(words)
    return words, frozenset(words[i:i + 3] for i in range(len(words) - 2))


class Similarity:
    """Word-level difflib ratio, with a word-3-gram prefilter so unrelated pairs cost ~nothing."""

    def __init__(self):
        self._cache: dict[tuple[str, str], float] = {}

    def ratio(self, a: str, b: str) -> float:
        key = (a, b)
        if key in self._cache:
            return self._cache[key]
        (wa, sa), (wb, sb) = _words_and_shingles(a), _words_and_shingles(b)
        if not wa and not wb:
            r = 1.0
        elif not wa or not wb:
            r = 0.0
        else:
            overlap = len(sa & sb) / max(1, min(len(sa), len(sb)))
            r = 0.0 if overlap < 0.08 else difflib.SequenceMatcher(None, wa, wb, autojunk=False).ratio()
        self._cache[key] = r
        return r


def pair_score(sim: Similarity, o: OldBlock, g: Block) -> float:
    """Matching score in [0, 1]; floats also count label / derived-id agreement."""
    if o.doc_type != g.doc_type:
        return 0.0
    if g.kind in ("table", "figure"):
        cap = sim.ratio(norm_plain(o.data.get("caption")), norm_plain(g.caption))
        if o.id == g.id_base or o.data.get("label") == g.label:
            cap = max(cap, 0.5 + 0.5 * cap)
        return cap
    return sim.ratio(norm_plain(o.data.get("text")), norm_plain(g.text))


def dp_align(olds: list[OldBlock], gens: list[Block], score, threshold: float) -> list[tuple[OldBlock, Block, float]]:
    n, m = len(olds), len(gens)
    S = [[0.0] * (m + 1) for _ in range(n + 1)]
    choice = [[0] * (m + 1) for _ in range(n + 1)]
    sc = [[score(o, g) for g in gens] for o in olds]
    for i in range(n - 1, -1, -1):
        for j in range(m - 1, -1, -1):
            best, ch = S[i + 1][j], 1
            if S[i][j + 1] > best:
                best, ch = S[i][j + 1], 2
            s = sc[i][j]
            if s >= threshold and S[i + 1][j + 1] + s > best:
                best, ch = S[i + 1][j + 1] + s, 3
            S[i][j], choice[i][j] = best, ch
    pairs, i, j = [], 0, 0
    while i < n and j < m:
        ch = choice[i][j]
        if ch == 3:
            pairs.append((olds[i], gens[j], sc[i][j]))
            i, j = i + 1, j + 1
        elif ch == 1:
            i += 1
        else:
            j += 1
    return pairs


@dataclass
class Result:
    final: list[Block]              # generated + hand-authored blocks in output order
    gen: Generated
    old: OldDoc
    status: dict[str, tuple[str, float, Block | None]]   # old id -> (status, sim, block)
    dropped: list[str]
    new_blocks: list[Block]
    retired: list[str]
    region: str
    figures_without_img: list[str]


def assign_ids(gen: Generated, old: OldDoc) -> Result:
    sim = Similarity()
    hand = [o for o in old.blocks if o.id in HAND_AUTHORED_IDS]
    candidates = [o for o in old.blocks if o.id not in HAND_AUTHORED_IDS]
    blocks = gen.blocks

    # Pass 1: order-preserving alignment of main blocks, then of footnote blocks.
    main_old = [o for o in candidates if o.kind != "footnote"]
    main_gen = [b for b in blocks if b.kind != "footnote"]
    fn_old = [o for o in candidates if o.kind == "footnote"]
    fn_gen = [b for b in blocks if b.kind == "footnote"]
    for olds, gens in ((main_old, main_gen), (fn_old, fn_gen)):
        for o, g, s in dp_align(olds, gens, lambda o, g: pair_score(sim, o, g), MATCH_THRESHOLD):
            g.old, g.match, g.sim = o, "in-order", s
    # Pass 2: order-free, for blocks that moved.
    matched_old = {id(b.old) for b in blocks if b.old is not None}
    rest_old = [o for o in candidates if id(o) not in matched_old]
    rest_gen = [b for b in blocks if b.old is None]
    scored = sorted(((pair_score(sim, o, g), o.index, k, o, g) for o in rest_old
                     for k, g in enumerate(rest_gen)), key=lambda t: (-t[0], t[1], t[2]))
    used_o, used_g = set(), set()
    for s, _, _, o, g in scored:
        if s < MOVED_THRESHOLD:
            break
        if id(o) in used_o or id(g) in used_g:
            continue
        used_o.add(id(o))
        used_g.add(id(g))
        g.old, g.match, g.sim = o, "moved", s

    # Ids: matched keep theirs; new ones never reuse any existing or retired id.
    taken = {o.id for o in old.blocks} | set(old.retired)
    for b in blocks:
        if b.old is not None:
            b.id = b.old.id
            if b.kind == "figure":
                b.img = b.old.data.get("img") or ""
    for b in blocks:
        if b.id is not None:
            continue
        if b.kind == "footnote":
            b.id = next_id(b.parent.id + "-fn", taken, numbered=True, sep="")
        else:
            b.id = next_id(b.id_base, taken, numbered=b.id_numbered)
        taken.add(b.id)

    # Hand-authored blocks: re-insert after the block that preceded them.
    final = list(blocks)
    by_old = {id(b.old): b for b in blocks if b.old is not None and b.match == "in-order"}
    placed_hand: dict[int, Block] = {}
    for h in hand:
        hb = Block("hand", h.data.get("section", ""), raw=h.raw, old=h, match="hand")
        hb.id, hb.h2, hb.h3 = h.id, h.data.get("h2"), h.data.get("h3")
        anchor = None
        for prev in reversed(old.blocks[:h.index]):
            anchor = by_old.get(id(prev)) or placed_hand.get(id(prev))
            if anchor is not None:
                break
        if anchor is None:
            pos = 0
        else:
            pos = final.index(anchor) + 1
            while pos < len(final) and final[pos].kind == "footnote" and final[pos].parent is anchor:
                pos += 1
            while pos < len(final) and final[pos].kind == "hand":
                pos += 1
        final.insert(pos, hb)
        placed_hand[id(h)] = hb

    # Headers: hand-authored claims first, then carry-forward placement.
    for hb in (b for b in final if b.kind == "hand"):
        for level in ("h2", "h3"):
            if not getattr(hb, level):
                continue
            g = next((g for g in gen.headers if not g.claimed and g.level == level
                      and g.section == hb.section and g.text == getattr(hb, level)), None)
            if g is None:
                gen.warnings.append(f"hand-authored block {hb.id!r} carries {level} {getattr(hb, level)!r}, "
                                    "which no longer matches any main.tex heading (shown as-is)")
            else:
                g.claimed = True
    for g in gen.headers:
        if g.claimed:
            continue
        cands = []
        for b in g.blocks:
            cands.append(b)
            if b.kind == "para":
                break
        if not cands:
            gen.warnings.append(f"heading {g.text!r} has no content block; it is not shown")
            continue
        owner = cands[0]
        for b in cands:
            if b.old is not None and b.old.data.get(g.level):
                owner = b
                break
        setattr(owner, g.level, g.text)

    # Status of every existing id.
    status: dict[str, tuple[str, float, Block | None]] = {}
    for b in final:
        if b.kind == "hand":
            status[b.id] = ("hand-authored, kept verbatim", 1.0, b)
        elif b.old is not None:
            s = Similarity().ratio(block_compare_text(b.old.data), block_compare_text(gen_dict(b)))
            status[b.old.id] = ("matched" if b.match == "in-order" else "matched (moved)", s, b)
    dropped = [o.id for o in old.blocks if o.id not in status]
    final_by_id = {b.id: b for b in final}
    for o in old.blocks:                               # header comment keys h:<id>
        if (o.data.get("h2") or o.data.get("h3")) and o.id in final_by_id:
            nb = final_by_id[o.id]
            if not (nb.h2 or nb.h3):
                dropped.append("h:" + o.id)
    new_blocks = [b for b in final if b.kind != "hand" and b.old is None]
    retired = sorted(set(old.retired) | {d for d in dropped if not d.startswith("h:")})
    figs = [b.id for b in final if b.kind == "figure" and not b.img]
    region = serialize_region(gen, final, retired)
    return Result(final, gen, old, status, dropped, new_blocks, retired, region, figs)


def next_id(base: str, taken: set[str], numbered: bool, sep: str = "-") -> str:
    if not numbered and base not in taken:
        return base
    pat = re.compile(re.escape(base) + re.escape(sep) + r"(\d+)$")
    nums = [int(m.group(1)) for t in taken if (m := pat.match(t))]
    k = max(nums, default=0 if numbered else 1) + 1
    while f"{base}{sep}{k}" in taken:
        k += 1
    return f"{base}{sep}{k}"


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------

def js_sq(s: str) -> str:
    s = s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r")
    return "'" + s.replace("</script", "<\\/script") + "'"


def js_tpl(s: str) -> str:
    s = s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    s = s.replace("</script", "<\\/script")
    return "`" + cites_to_template(s) + "`"


def js_json(v) -> str:
    return json.dumps(v, ensure_ascii=False).replace("</script", "<\\/script")


def js_key(k: str) -> str:
    return k if re.fullmatch(r"[A-Za-z_$][\w$]*", k) else js_sq(k)


def serialize_block(b: Block) -> str:
    if b.kind == "hand":
        return b.raw + ","
    parts = [f"id: {js_sq(b.id)}"]
    if b.kind in ("para", "footnote"):
        parts.append(f"tex: {js_tpl(b.tex or '')}")
    parts.append(f"section: {js_sq(b.section)}")
    if b.h2:
        parts.append(f"h2: {js_sq(b.h2)}")
    if b.h3:
        parts.append(f"h3: {js_sq(b.h3)}")
    if b.kind == "table":
        parts += ["type: 'table'", f"label: {js_sq(b.label)}", f"caption: {js_tpl(b.caption or '')}",
                  f"headers: {js_json(b.headers)}", f"rows: {js_json(b.rows)}"]
    elif b.kind == "figure":
        parts += ["type: 'figure'", f"label: {js_sq(b.label)}", f"caption: {js_tpl(b.caption or '')}",
                  f"img: {js_sq(b.img or '')}"]
    else:
        parts.append(f"text: {js_tpl(b.text or '')}")
    return "{ " + ", ".join(parts) + " },"


def serialize_region(gen: Generated, final: list[Block], retired: list[str]) -> str:
    lines = [BEGIN_MARKER, "const CITES = {"]
    lines += [f"  {js_key(k)}: {js_sq(v)}," for k, v in gen.cites.items()]
    lines += ["};", CITE_FN, "", "const SECTIONS = ["]
    used = {b.section for b in final}
    lines += [f"  {{ id: {js_sq(s['id'])}, label: {js_sq(s['label'])} }},"
              for s in gen.sections if s["id"] in used]
    lines += ["];", ""]
    if retired:
        lines.append(RETIRED_PREFIX + ", ".join(retired))
    lines.append("const DOC = [")
    lines += [serialize_block(b) for b in final]
    lines += ["];", END_MARKER]
    return "\n".join(lines)


def apply_region(old: OldDoc, region: str) -> str:
    return old.html[:old.region_start] + region + old.html[old.region_end:]


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def word_diff(a: str, b: str, context: int = 4) -> str:
    A, B = a.split(), b.split()
    out = []
    ops = difflib.SequenceMatcher(None, A, B, autojunk=False).get_opcodes()

    def clip(ws: list[str]) -> str:
        return " ".join(ws) if len(ws) <= 40 else " ".join(ws[:25]) + f" ...({len(ws) - 35} words)... " + " ".join(ws[-10:])
    for k, (tag, i1, i2, j1, j2) in enumerate(ops):
        if tag == "equal":
            seg = A[i1:i2]
            head = seg[:context] if k > 0 else []
            tail = seg[-context:] if k < len(ops) - 1 else []
            if len(seg) <= 2 * context and 0 < k < len(ops) - 1:
                out.append(" ".join(seg))
            else:
                out.append(" ".join(head) + (" ... " if len(seg) > len(head) + len(tail) else " ") + " ".join(tail))
            continue
        if i2 > i1:
            out.append("[-" + clip(A[i1:i2]) + "-]")
        if j2 > j1:
            out.append("{+" + clip(B[j1:j2]) + "+}")
    return collapse_ws(" ".join(out))


def build_report(res: Result, args) -> str:
    L: list[str] = []
    old, gen = res.old, res.gen
    n_old = len(old.blocks)
    counts: dict[str, int] = {}
    for st, _, _ in res.status.values():
        counts[st] = counts.get(st, 0) + 1
    L.append("== margin_notes DOC regeneration report ==")
    L.append(f"source: {args.tex}  |  existing DOC blocks: {n_old}  |  generated DOC blocks: {len(res.final)}")
    L.append("summary: " + ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))
             + f", {len([d for d in res.dropped if not d.startswith('h:')])} DROPPED"
             + f" (+{len([d for d in res.dropped if d.startswith('h:')])} header keys)"
             + f", {len(res.new_blocks)} new")
    if res.dropped:
        L.append("!!! DROPPED IDS PRESENT -- see (b) below; --write will refuse without --allow-drop !!!")
    L.append("")
    L.append("(a) existing ids")
    for o in old.blocks:
        st = res.status.get(o.id)
        if st is None:
            L.append(f"  {o.id:34s} DROPPED")
        else:
            L.append(f"  {o.id:34s} {st[0]:30s} sim={st[1]:.3f}")
    L.append("")
    if res.dropped:
        L.append("!" * 78)
        L.append("!!! (b) DROPPED IDS -- reviewer comments on these would be ORPHANED:")
        for d in res.dropped:
            o = old.by_id().get(d[2:] if d.startswith("h:") else d)
            what = ("header comment key (block no longer carries a heading)" if d.startswith("h:")
                    else collapse_ws(block_compare_text(o.data))[:90] if o else "")
            L.append(f"!!!   {d:34s} {what}")
        L.append("!!! --write refuses unless: --allow-drop " + ",".join(res.dropped))
        L.append("!" * 78)
    else:
        L.append("(b) dropped ids: none (every existing id, and every h:<id> header key, is carried forward)")
    L.append("")
    L.append("(c) new ids")
    if not res.new_blocks:
        L.append("  (none)")
    for b in res.new_blocks:
        L.append(f"  {b.id:34s} {b.kind:8s} {block_compare_text(gen_dict(b))[:80]}")
    L.append("")
    L.append(f"(d) text differences vs the current hand mirror (matched blocks with sim < {DIFF_REPORT_BELOW}), "
             "largest first")
    diffs = sorted(((s, oid, b) for oid, (st, s, b) in res.status.items()
                    if st.startswith("matched") and s < DIFF_REPORT_BELOW), key=lambda t: t[0])
    if not diffs:
        L.append("  (none)")
    for s, oid, b in diffs:
        a_txt = block_compare_text(b.old.data)
        b_txt = block_compare_text(gen_dict(b))
        L.append(f"  --- {oid}  sim={s:.3f}  ({res.status[oid][0]})")
        L.append("      " + word_diff(a_txt, b_txt))
        for lvl in ("h2", "h3"):
            if b.old.data.get(lvl) and getattr(b, lvl) and b.old.data.get(lvl) != getattr(b, lvl):
                L.append(f"      {lvl}: [-{b.old.data.get(lvl)}-] {{+{getattr(b, lvl)}+}}")
    L.append("")
    L.append("figures")
    for b in res.final:
        if b.kind == "figure":
            L.append(f"  {b.id:34s} {b.label:10s} " + ("img carried forward" if b.img else "NO IMAGE (add one by hand)"))
    L.append("")
    L.append("CITES changes vs current file")
    changes = []
    for k in sorted(set(old.cites) | set(gen.cites)):
        a, c = old.cites.get(k), gen.cites.get(k)
        if a != c:
            changes.append(f"  {k}: {a!r} -> {c!r}")
    L += changes or ["  (none)"]
    L.append("SECTIONS changes vs current file")
    osec = [(s["id"], s["label"]) for s in old.sections]
    nsec = [(s["id"], s["label"]) for s in gen.sections if any(b.section == s["id"] for b in res.final)]
    L += ([f"  old: {osec}", f"  new: {nsec}"] if osec != nsec else ["  (none)"])
    if gen.warnings:
        L.append("")
        L.append("warnings")
        L += [f"  - {w}" for w in gen.warnings]
    return "\n".join(L)


# ---------------------------------------------------------------------------
# node verification (optional; used by --report)
# ---------------------------------------------------------------------------

NODE_EVAL = r"""
const fs = require('fs');
const html = fs.readFileSync(process.argv[2], 'utf8');
const b = html.indexOf(process.argv[3]);
const e = html.indexOf(process.argv[4], b);
const region = html.slice(b, e);
const r = new Function(region + '\nreturn {CITES, SECTIONS, DOC};')();
for (const d of r.DOC) { if (d.img) d.img = d.img.length; }
// the whole main <script> must at least compile
const s = html.lastIndexOf('<script>', b);
const t = html.indexOf('</script>', b);
new Function(html.slice(s + 8, t));
process.stdout.write(JSON.stringify(r));
"""


def verify_with_node(preview: Path, final: list[Block], build_chunks: Path) -> list[str]:
    msgs: list[str] = []
    node = shutil.which("node")
    if node is None:
        return ["node not found on PATH: skipped build_chunks.js / script parse checks"]
    with tempfile.TemporaryDirectory(prefix="mn_verify_") as td:
        tdp = Path(td)
        shutil.copyfile(preview, tdp / "margin_notes.html")
        shutil.copyfile(build_chunks, tdp / "build_chunks.js")
        (tdp / "eval.js").write_text(NODE_EVAL, encoding="utf-8")
        p = subprocess.run([node, "build_chunks.js"], cwd=td, capture_output=True, text=True, encoding="utf-8")
        m = re.search(r"found (\d+) top-level DOC elements", p.stdout)
        if p.returncode != 0 or not m:
            msgs.append(f"FAIL build_chunks.js (exit {p.returncode}): {p.stderr.strip()[:400]}")
        elif int(m.group(1)) != len(final):
            msgs.append(f"FAIL build_chunks.js found {m.group(1)} elements, expected {len(final)}")
        else:
            nchunks = len(list((tdp / "dist" / "chunks").glob("*.js")))
            msgs.append(f"ok   build_chunks.js parsed {m.group(1)} DOC elements into {nchunks} chunk files")
        p = subprocess.run([node, "eval.js", "margin_notes.html", BEGIN_MARKER, END_MARKER], cwd=td,
                           capture_output=True, text=True, encoding="utf-8")
        if p.returncode != 0:
            msgs.append(f"FAIL generated <script> does not evaluate: {p.stderr.strip()[:600]}")
            return msgs
        data = json.loads(p.stdout)
        ids = [d["id"] for d in data["DOC"]]
        if ids != [b.id for b in final]:
            msgs.append("FAIL node-evaluated DOC ids differ from the generator's list")
        elif len(set(ids)) != len(ids):
            msgs.append("FAIL duplicate DOC ids")
        else:
            bad = []
            for d, b in zip(data["DOC"], final):
                if b.kind in ("para", "footnote"):
                    want = re.sub(CITE_OPEN + r"([^" + CITE_CLOSE + r"]*)" + CITE_CLOSE,
                                  lambda m: ' <cite contenteditable="false">(' + "; ".join(
                                      data["CITES"].get(k, k) for k in m.group(1).split(",")) + ")</cite>",
                                  b.text or "")
                    if d.get("text") != want or d.get("tex") != b.tex:
                        bad.append(b.id)
            msgs.append(f"FAIL text/tex round-trip mismatch: {bad[:8]}" if bad else
                        f"ok   generated <script> compiles; node-evaluated DOC ({len(ids)} blocks) round-trips "
                        "text/tex exactly")
    return msgs


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def generate(args) -> Result:
    html = Path(args.html).read_bytes().decode("utf-8")
    old = parse_old_doc(html)
    gen = DocBuilder(Path(args.tex), Path(args.aux), Path(args.bib), Path(args.numbers), old).build()
    res = assign_ids(gen, old)
    if html.count("\r\n") * 2 > html.count("\n"):           # keep a CRLF file CRLF throughout
        res.region = res.region.replace("\r\n", "\n").replace("\n", "\r\n")
    return res


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--report", action="store_true", help="(default) print the carry-forward report; "
                      "write generated_preview.html; never touch margin_notes.html")
    mode.add_argument("--check", action="store_true", help="exit 1 if the generated region is stale")
    mode.add_argument("--write", action="store_true", help="update margin_notes.html in place")
    ap.add_argument("--allow-drop", default="", help="comma-separated existing ids --write may drop")
    ap.add_argument("--tex", default=str(DEFAULT_TEX))
    ap.add_argument("--aux", default=str(DEFAULT_AUX))
    ap.add_argument("--bib", default=str(DEFAULT_BIB))
    ap.add_argument("--numbers", default=str(DEFAULT_NUMBERS))
    ap.add_argument("--html", default=str(DEFAULT_HTML))
    ap.add_argument("--preview", default=str(DEFAULT_PREVIEW))
    ap.add_argument("--no-node", action="store_true", help="skip the node-based verification in --report")
    args = ap.parse_args(argv)
    for stream in (sys.stdout, sys.stderr):      # never crash on a console codepage
        try:
            stream.reconfigure(encoding="utf-8" if not stream.isatty() else stream.encoding,
                               errors="replace")
        except (AttributeError, ValueError):
            pass

    if args.check:
        html = Path(args.html).read_bytes().decode("utf-8")
        if BEGIN_MARKER not in html or ("\n" + END_MARKER) not in html:
            print(f"check: GENERATED markers missing in {args.html}; run "
                  "`python tools/margin_notes/build_doc_from_tex.py --write` once", file=sys.stderr)
            return 1
    try:
        res = generate(args)
    except GenerationError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1 if args.check else 2
    current = res.old.html[res.old.region_start:res.old.region_end]

    if args.check:
        if current == res.region:
            print("check: margin_notes.html generated region is up to date")
            return 0
        a, b = current.splitlines(), res.region.splitlines()
        first = next((k for k, (x, y) in enumerate(zip(a, b)) if x != y), min(len(a), len(b)))
        print(f"check: margin_notes.html generated region is STALE (first difference at region line {first + 1});"
              " run build_doc_from_tex.py --report, then --write", file=sys.stderr)
        return 1

    if args.write:
        allowed = {x.strip() for x in args.allow_drop.split(",") if x.strip()}
        missing = [d for d in res.dropped if d not in allowed]
        if missing:
            print("refusing to --write: these existing ids would be dropped (orphaning their comments): "
                  + ", ".join(missing) + "\nre-run with --allow-drop " + ",".join(missing)
                  + " if that is intended", file=sys.stderr)
            return 1
        new_html = apply_region(res.old, res.region)
        if new_html == res.old.html:
            print("write: already up to date")
            return 0
        Path(args.html).write_bytes(new_html.encode("utf-8"))
        print(f"write: updated {args.html} ({len(res.final)} blocks, {len(res.new_blocks)} new, "
              f"{len(res.dropped)} dropped)")
        return 0

    print(build_report(res, args))
    preview = Path(args.preview)
    preview.write_bytes(apply_region(res.old, res.region).encode("utf-8"))
    print(f"\nwrote preview: {preview}")
    if not args.no_node:
        for msg in verify_with_node(preview, res.final, HERE / "build_chunks.js"):
            print("node: " + msg)
    return 0


if __name__ == "__main__":
    sys.exit(main())
