"""Generate paper/numbers.tex from paper/numbers.json, the single source of
truth for every reported value in main.tex. main.tex writes \\val{key}, never
the digits, so a value changes in exactly one place.

Usage:
  python gen_numbers.py                 write numbers.tex
  python gen_numbers.py --check         exit 1 if numbers.tex is stale or numbers.json is invalid
  python gen_numbers.py --verify-sources
                                        re-read each value's recorded source file and report
                                        any value that no longer matches it
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
NUMBERS_JSON = HERE / "numbers.json"
NUMBERS_TEX = HERE / "numbers.tex"

KEY_RE = re.compile(r"^[a-z0-9_]+(\.[a-z0-9_]+)+$")
STATUSES = {"verified", "derived", "mismatch", "doc_only", "untraceable"}


def load_numbers(path: Path | None = None) -> dict[str, dict]:
    path = path or NUMBERS_JSON
    data = json.loads(path.read_text(encoding="utf-8"))
    values = data.get("values")
    if not isinstance(values, dict):
        raise ValueError(f"{path.name}: top-level 'values' object missing")
    problems = []
    for key, entry in values.items():
        if not KEY_RE.match(key):
            problems.append(f"bad key syntax: {key!r}")
        if not isinstance(entry, dict) or not isinstance(entry.get("value"), str) or not entry["value"]:
            problems.append(f"{key}: 'value' must be a non-empty string")
            continue
        if any(c in entry["value"] for c in "\\$%#&"):
            problems.append(f"{key}: value {entry['value']!r} contains a LaTeX special character")
        status = entry.get("status")
        if status not in STATUSES:
            problems.append(f"{key}: status {status!r} not one of {sorted(STATUSES)}")
    if problems:
        raise ValueError(f"{path.name} is invalid:\n  " + "\n  ".join(problems))
    return values


def render_tex(values: dict[str, dict]) -> str:
    lines = [
        "% GENERATED by paper/gen_numbers.py from paper/numbers.json -- do not edit by hand.",
        "% Every reported value in main.tex is written \\val{key}; change the value in",
        "% numbers.json and re-run gen_numbers.py (build.ps1 does this automatically).",
        "\\makeatletter",
        "\\DeclareRobustCommand{\\val}[1]{\\@ifundefined{pv@#1}%",
        "  {\\PackageError{numbers}{Unknown value key `#1'}{Add it to paper/numbers.json and run gen_numbers.py}}%",
        "  {\\@nameuse{pv@#1}}}",
    ]
    for key in sorted(values):
        lines.append(f"\\@namedef{{pv@{key}}}{{{values[key]['value']}}}")
    lines.append("\\makeatother")
    return "\n".join(lines) + "\n"


def numeric(tex_value: str) -> float | None:
    s = tex_value.replace("{,}", "").replace(",", "")
    try:
        return float(s)
    except ValueError:
        return None


def resolve_locator(obj, locator: str):
    """Follow a dotted path. On a list, a segment is either an index or a
    selector `field=value[,field=value]` picking the one element that matches
    (e.g. groups[family=section_reorder,k_pairs=4].p_value). Bracketed
    segments may contain dots ([a.b])."""
    cur = obj
    for part in re.findall(r"\[([^\]]+)\]|([^.\[\]]+)", locator):
        seg = part[0] or part[1]
        if isinstance(cur, list):
            if "=" in seg:
                conds = [c.split("=", 1) for c in seg.split(",")]
                hits = [x for x in cur if isinstance(x, dict)
                        and all(str(x.get(k.strip())) == v.strip() for k, v in conds)]
                if len(hits) != 1:
                    raise KeyError(f"selector [{seg}] matched {len(hits)} elements")
                cur = hits[0]
            else:
                cur = cur[int(seg)]
        else:
            cur = cur[seg]
    return cur


def matches_printed(printed: str, source_value) -> bool:
    """True if source_value rounds to the printed value, allowing for a
    proportion printed as a percentage."""
    p = numeric(printed)
    try:
        s = float(source_value)
    except (TypeError, ValueError):
        return str(source_value).strip() == printed.strip()
    if p is None:
        return False
    decimals = len(printed.split(".")[1]) if "." in printed else 0
    tol = 0.5 * 10 ** (-decimals) + 1e-9
    return any(math.isclose(p, c, abs_tol=tol) or abs(p - c) <= tol for c in (s, s * 100))


def verify_sources(values: dict[str, dict]) -> int:
    failures = 0
    checked = 0
    for key in sorted(values):
        src = values[key].get("source") or {}
        rel = src.get("file")
        loc = src.get("locator")
        if not rel or not loc or src.get("format", "json") != "json":
            continue
        path = (HERE / rel).resolve()
        if not path.exists():
            print(f"MISSING SOURCE  {key}: {rel}")
            failures += 1
            continue
        want_sha = src.get("sha256")
        if want_sha and hashlib.sha256(path.read_bytes()).hexdigest() != want_sha:
            print(f"SOURCE CHANGED  {key}: {rel} no longer has the recorded sha256")
            failures += 1
        try:
            got = resolve_locator(json.loads(path.read_text(encoding="utf-8")), loc)
        except (KeyError, IndexError, ValueError, TypeError) as exc:
            print(f"BAD LOCATOR     {key}: {rel} :: {loc} ({exc})")
            failures += 1
            continue
        checked += 1
        if not matches_printed(values[key]["value"], got):
            print(f"VALUE MISMATCH  {key}: paper prints {values[key]['value']}, source has {got}")
            failures += 1
    print(f"verified {checked} machine-readable sources; {failures} problem(s)")
    return failures


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--verify-sources", action="store_true")
    args = ap.parse_args()
    try:
        values = load_numbers()
    except (ValueError, json.JSONDecodeError) as exc:
        print(exc)
        return 1
    if args.verify_sources:
        return 1 if verify_sources(values) else 0
    tex = render_tex(values)
    if args.check:
        current = NUMBERS_TEX.read_text(encoding="utf-8") if NUMBERS_TEX.exists() else ""
        if current != tex:
            print("numbers.tex is stale: run `python paper/gen_numbers.py`")
            return 1
        return 0
    NUMBERS_TEX.write_text(tex, encoding="utf-8", newline="\n")
    print(f"wrote {NUMBERS_TEX.name} ({len(values)} values)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
